### ISSUE TITLE
Notify users before drawing

### ISSUE THREAD

**Issue by tomekpilat** [IDCracow/parkspoty2#36]
Admin should be able to notify those users who pick 'remind me about drawing' function. It may give them a chance to resign for particular month.
- [ ] organize data storage for notification log
- [ ] keep the information about date and time when notification was sent (to avoid annoying messages)

**Comment by tomekpilat** [comment]
We should use one of the modules that Parse offers: https://www.parse.com/docs/js/guide#cloud-code-modules, need to be investigated which one fits and which is easiest to implement: mailgun, mandrill or sendgrid.

**Comment by marziolek** [comment]
Job fixed for every 24th day of month
